# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'Roommate App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roommate App
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Auth'
  
  target 'Roommate AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Roommate AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
